### PR TITLE
removed old button, added chatlio

### PR DESCRIPTION
**Pull request by mashhoodr**
Added chatlio

### CODE REVIEW

**Comment by fryclukasz** [comment]
@mashhoodr I don't know why, but I do not see the chatlio widget

image


Also, could you make it the same style as we have on the dashboard? See https://github.com/testmunk/aft-backend/commit/954884d5d91699c9e7b3a9fc17661c22a8149fda

**Comment by mashhoodr** [comment]
You will see it when it is deployed. Added the CSS.

**Comment by fryclukasz** [comment]
@mashhoodr so I cannot test the changes locally?

**Comment by mashhoodr** [comment]
you can if you serve the folder over a webserver

**Comment by fryclukasz** [comment]
@mashhoodr thanks. Works now. 

The last thing, can you update the css? I think Stefan has changed the **fonts**. See how it looks on the dashboard on staging:

screen_shot_2015-04-16_at_15_57_27


Here is that PR: https://github.com/testmunk/aft-backend/pull/131

**Comment by fryclukasz** [comment]
Or maybe it's not necessary. @mposchen what do you think about the chatlio style (fonts, colours)?

**Comment by mposchen** [comment]
I'm ok with the normal font for this widget.

**Comment by fryclukasz** [comment]
@mposchen @mashhoodr ok, so it can be merged. But, let's wait until Chatlio widget on the dashboard will be on prod

**Pull request merged**
