### PR TITLE
Add video about Calabash integration

### PR DESCRIPTION
**Pull request by lukasfr**
image

@mposchen have a look. Do you like it this way?

https://www.pivotaltracker.com/story/show/109410274

### CODE REVIEW

**Comment by lukasfr** [comment]
@mposchen It's an embedded video. Can be played :)

**Comment by mposchen** [comment]
@lukasfr ok. I assume there's a video play button so people know it's a video. If not you can add this 'play' attribute as html or we need an image.

**Comment by mposchen** [comment]
@lukasfr also I'm wondering if it would be smarter to host the video on our space? - since we don't know how long Joshua will keep it up.

**Comment by lukasfr** [comment]
@mposchen yes, there is a play button

image


I don't have any idea how to save this video http://www.screencast.com/users/joshua.moody/folders/Calabash/media/a5477200-b041-4bc3-ba2d-643111771135/embed
@Djokic? 

For now, I'd just use it this way

**Comment by lukasfr** [comment]
@Djokic @mposchen ping

**Comment by mposchen** [comment]
@Djokic please check it and merge if okay.

**Comment by Djokic** [comment]
@lukasfr @mposchen Here is link to source video file http://content.screencast.com/users/joshua.moody/folders/Calabash/media/a5477200-b041-4bc3-ba2d-643111771135/2015-10-21_18-29-18.mp4. It would be good that we host it on our Vimeo, in case this one becomes inactive.

What do you think?

**Comment by mposchen** [comment]
yes @Djokic agree. Vimeo login details are on meldium.

**Comment by Djokic** [comment]
@mposchen I've uploaded video to Testmunk Vimeo account and updated it source in docs. 
Please review and merge it.

screenshot from 2016-02-29 08 11 35

**Pull request merged**
