### PR TITLE
[API] Added links to API calls in the introduction

### PR DESCRIPTION
**Pull request by fryclukasz**
image

@mposchen please have a look

### CODE REVIEW

**Comment by mposchen** [comment]
Some design styling needed.
screen shot 2015-06-09 at 11 10 10 am

**Comment by fryclukasz** [comment]
I've already thought about it. But, it's really hard to do it in rst (Sphinx). It's a language I don't know. And, as I see there is no way to remove those spaces.

We can either stick with it or have:

screen shot 2015-06-09 at 23 54 12

or 

screen shot 2015-06-09 at 23 57 21

@mposchen let me know

**Comment by fryclukasz** [comment]
I feel that the best option is still the 1th one

**Comment by fryclukasz** [comment]
@ysilyutin @mposchen unfortunately, after trying "•" the space is still there

image

**Comment by mposchen** [comment]
@fryclukasz have a look how they do it here: https://docs.readthedocs.org/en/latest/index.html

screen shot 2015-06-09 at 4 38 56 pm

**Comment by mposchen** [comment]
the language is "rst" http://stackoverflow.com/questions/2471804/using-sphinx-with-markdown-instead-of-rst

**Comment by fryclukasz** [comment]
re sphinx and markdown, it will be even more work with *hacking* this

**Comment by fryclukasz** [comment]
I've checked you links (https://docs.readthedocs.org/en/latest/index.html) but still I don't know how to do it. It's damn hard to learn another language. 

I don't want to spend half a day of trying to find solution. 

This is like a **main** table of content:  
image

We also have it:

image

But, I don't have any idea how to have such formatting in lists. @mashhoodr what do you think?


@mposchen In my opinion we are overthinking it. Time spent / value is negative.

**Comment by fryclukasz** [comment]
It's also down to css how it's rendered. I don't have any idea how to modify this theme not to include those `blockquote`

screen shot 2015-06-10 at 10 42 04

**Pull request merged**
